### PR TITLE
Port to python 3

### PR DESCRIPTION
**Pull request by rgeoghegan**
These changes will make pycco work in python 3.

### CODE REVIEW

**Comment by patrickayoup** [comment]
Is there any possibility of this being merged? Python 3 support would be fantastic!

**Comment by treyhunner** [comment]
I am not merging anything because I have not used this project in many months and do not have time to test pull requests before merging.

@patrickayoup if you or someone else would like to take over the responsibility of merging pull requests I'm happy to work with Nick to grant you access.

**Comment by patrickayoup** [comment]
@treyhunner I no longer need this. I have found another project to satisfy my requirements.

thank you.

**Comment by skorokithakis** [comment]
@patrickayoup, can you share which project you found? I find pycco very useful but the fact that it's no longer maintained is regrettable.

@treyhunner, can you at least merge this PR and make a release so pycco at least works with Python 3? For what it's worth, I tested it and it seems to work fine.

**Comment by subsetpark** [comment]
Hi @skorokithakis, I've recently agreed to pitch in with maintaining this project. It will take me a little while to spin up a test suite suitable for testing PRs against, but once I do you can be sure this will a top priority for me.

**Comment by skorokithakis** [comment]
Great, thank you! I'll open an issue for the superfluous amounts of vertical white space pycco seems to leave.

**Comment by subsetpark** [comment]
I've rolled Python 3 support into my most recent update. @rgeoghegan thanks for your PR!

**Pull request closed without merging**
